### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by wemeetagain** [tabcat/error-code#2]
Just looking over your package. Thanks for taking the initiative on this.

Two small suggestions, nothing critical:
- Use named export instead of default export. I've seen better IDE auto-completion support with named exports. And it leads to more uniform downstream code when the upstream variable name is used across all consumer code.
- Rename `ErrorCode` to `CodeError`. Since this is meant to be used like `Error`, `TypeError`, etc, I think you should stick with the convention of `${Foo}Error` so it is more clear that the exported object is a subclass of `Error`.

**Comment by tabcat** [comment]
Will make the changes
